version: '3'
services:
  nginx:
      # use image nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
          - 443:443
      # mount directories
      volumes:
          - ./hosts:/etc/nginx/conf.d
          - ./logs:/var/log/nginx
          - ./data:/var/www/public
